In [1]:
import pandas as pd

df = pd.read_excel("../data/raw/Online_Retail.xlsx")

print("Before:", df.shape)

df = df.dropna(subset=["CustomerID"])

df = df[~df["InvoiceNo"].astype(str).str.startswith("C")]

df = df[(df["Quantity"] > 0) & (df["UnitPrice"] > 0)]

df = df.drop_duplicates()

print("After:", df.shape)

df.head()

Before: (541909, 8)
After: (392692, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [2]:
basket = (
    df.groupby(['InvoiceNo', 'Description'])['Quantity']
    .sum()
    .unstack()
    .fillna(0)
)

basket.head()

Description,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,I LOVE LONDON MINI RUCKSACK,NINE DRAWER OFFICE TIDY,OVAL WALL MIRROR DIAMANTE,RED SPOT GIFT BAG LARGE,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,...,ZINC STAR T-LIGHT HOLDER,ZINC SWEETHEART SOAP DISH,ZINC SWEETHEART WIRE LETTER RACK,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC TOP 2 DOOR WOODEN SHELF,ZINC WILLIE WINKIE CANDLE STICK,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536365,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536366,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536367,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536368,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536369,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
basket = basket.applymap(lambda x: 1 if x > 0 else 0)

basket.head()

C:\Users\Ziad\AppData\Local\Temp\ipykernel_17084\2737237846.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  basket = basket.applymap(lambda x: 1 if x > 0 else 0)

Description,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,I LOVE LONDON MINI RUCKSACK,NINE DRAWER OFFICE TIDY,OVAL WALL MIRROR DIAMANTE,RED SPOT GIFT BAG LARGE,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,...,ZINC STAR T-LIGHT HOLDER,ZINC SWEETHEART SOAP DISH,ZINC SWEETHEART WIRE LETTER RACK,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC TOP 2 DOOR WOODEN SHELF,ZINC WILLIE WINKIE CANDLE STICK,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536365,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536366,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536367,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536368,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536369,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
basket.iloc[:5, :10]

Description,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,I LOVE LONDON MINI RUCKSACK,NINE DRAWER OFFICE TIDY,OVAL WALL MIRROR DIAMANTE,RED SPOT GIFT BAG LARGE,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET
InvoiceNo,,,,,,,,,,
536365,0,0,0,0,0,0,0,0,0,0
536366,0,0,0,0,0,0,0,0,0,0
536367,0,0,0,0,0,0,0,0,0,0
536368,0,0,0,0,0,0,0,0,0,0
536369,0,0,0,0,0,0,0,0,0,0

In [5]:
basket.sum().sort_values(ascending=False).head(10)

Description
WHITE HANGING HEART T-LIGHT HOLDER    1971
REGENCY CAKESTAND 3 TIER              1703
JUMBO BAG RED RETROSPOT               1600
PARTY BUNTING                         1379
ASSORTED COLOUR BIRD ORNAMENT         1375
LUNCH BAG RED RETROSPOT               1288
SET OF 3 CAKE TINS PANTRY DESIGN      1146
POSTAGE                               1099
LUNCH BAG  BLACK SKULL.               1052
PACK OF 72 RETROSPOT CAKE CASES       1029
dtype: int64

In [7]:
!pip install mlxtend

Collecting mlxtend
  Using cached mlxtend-0.24.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: scipy>=1.16.3 in c:\users\ziad\appdata\roaming\python\python313\site-packages (from mlxtend) (1.16.3)
Collecting numpy>=2.3.5 (from mlxtend)
  Using cached numpy-2.4.5-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Collecting pandas>=2.3.3 (from mlxtend)
  Downloading pandas-3.0.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: scikit-learn>=1.8.0 in c:\users\ziad\appdata\roaming\python\python313\site-packages (from mlxtend) (1.8.0)
Collecting matplotlib>=3.10.8 (from mlxtend)
  Downloading matplotlib-3.10.9-cp313-cp313-win_amd64.whl.metadata (52 kB)
Requirement already satisfied: joblib>=1.5.2 in c:\users\ziad\appdata\roaming\python\python313\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\ziad\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\ziad\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\ziad\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\ziad\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\ziad\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\ziad\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (11.1.0)
Requirement already satisfied: pyparsing>=3 in c:\users\ziad\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\ziad\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\ziad\anaconda3\lib\site-packages (from pandas>=2.3.3->mlxtend) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\ziad\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\ziad\appdata\roaming\python\python313\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)
Using cached mlxtend-0.24.0-py3-none-any.whl (1.4 MB)
Downloading matplotlib-3.10.9-cp313-cp313-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.2 MB 1.5 MB/s eta 0:00:06
   --- ------------------------------------ 0.8/8.2 MB 1.4 MB/s eta 0:00:06
   ----- ---------------------------------- 1.0/8.2 MB 1.2 MB/s eta 0:00:07
   ----- ---------------------------------- 1.0/8.2 MB 1.2 MB/s eta 0:00:07
   ----- ---------------------------------- 1.0/8.2 MB 1.2 MB/s eta 0:00:07
   ------ --------------------------------- 1.3/8.2 MB 905.3 kB/s eta 0:00:08
   ------ --------------------------------- 1.3/8.2 MB 905.3 kB/s eta 0:00:08
   ------- -------------------------------- 1.6/8.2 MB 752.1 kB/s eta 0:00:09
   ------- -------------------------------- 1.6/8.2 MB 752.1 kB/s eta 0:00:09
   ------- -------------------------------- 1.6/8.2 MB 752.1 kB/s eta 0:00:09
   ------- -------------------------------- 1.6/8.2 MB 752.1 kB/s eta 0:00:09
   -------- ------------------------------- 1.8/8.2 MB 634.4 kB/s eta 0:00:11
   -------- ------------------------------- 1.8/8.2 MB 634.4 kB/s eta 0:00:11
   -------- ------------------------------- 1.8/8.2 MB 634.4 kB/s eta 0:00:11
   -------- ------------------------------- 1.8/8.2 MB 634.4 kB/s eta 0:00:11
   -------- ------------------------------- 1.8/8.2 MB 634.4 kB/s eta 0:00:11
   ---------- ----------------------------- 2.1/8.2 MB 532.9 kB/s eta 0:00:12
   ---------- ----------------------------- 2.1/8.2 MB 532.9 kB/s eta 0:00:12
   ---------- ----------------------------- 2.1/8.2 MB 532.9 kB/s eta 0:00:12
   ---------- ----------------------------- 2.1/8.2 MB 532.9 kB/s eta 0:00:12
   ---------- ----------------------------- 2.1/8.2 MB 532.9 kB/s eta 0:00:12
   ----------- ---------------------------- 2.4/8.2 MB 470.0 kB/s eta 0:00:13
   ----------- ---------------------------- 2.4/8.2 MB 470.0 kB/s eta 0:00:13
   ----------- ---------------------------- 2.4/8.2 MB 470.0 kB/s eta 0:00:13
   ----------- ---------------------------- 2.4/8.2 MB 470.0 kB/s eta 0:00:13
   ------------ --------------------------- 2.6/8.2 MB 438.7 kB/s eta 0:00:13
   ------------ --------------------------- 2.6/8.2 MB 438.7 kB/s eta 0:00:13
   ------------ --------------------------- 2.6/8.2 MB 438.7 kB/s eta 0:00:13
   ------------ --------------------------- 2.6/8.2 MB 438.7 kB/s eta 0:00:13
   ------------ --------------------------- 2.6/8.2 MB 438.7 kB/s eta 0:00:13
   -------------- ------------------------- 2.9/8.2 MB 408.3 kB/s eta 0:00:14
   -------------- ------------------------- 2.9/8.2 MB 408.3 kB/s eta 0:00:14
   -------------- ------------------------- 2.9/8.2 MB 408.3 kB/s eta 0:00:14
   -------------- ------------------------- 2.9/8.2 MB 408.3 kB/s eta 0:00:14
   -------------- ------------------------- 2.9/8.2 MB 408.3 kB/s eta 0:00:14
   --------------- ------------------------ 3.1/8.2 MB 384.3 kB/s eta 0:00:14
   --------------- ------------------------ 3.1/8.2 MB 384.3 kB/s eta 0:00:14
   --------------- ------------------------ 3.1/8.2 MB 384.3 kB/s eta 0:00:14
   --------------- ------------------------ 3.1/8.2 MB 384.3 kB/s eta 0:00:14
   --------------- ------------------------ 3.1/8.2 MB 384.3 kB/s eta 0:00:14
   ---------------- ----------------------- 3.4/8.2 MB 366.2 kB/s eta 0:00:14
   ---------------- ----------------------- 3.4/8.2 MB 366.2 kB/s eta 0:00:14
   ---------------- ----------------------- 3.4/8.2 MB 366.2 kB/s eta 0:00:14
   ---------------- ----------------------- 3.4/8.2 MB 366.2 kB/s eta 0:00:14
   ---------------- ----------------------- 3.4/8.2 MB 366.2 kB/s eta 0:00:14
   ----------------- ---------------------- 3.7/8.2 MB 354.6 kB/s eta 0:00:13
   ----------------- ---------------------- 3.7/8.2 MB 354.6 kB/s eta 0:00:13
   ----------------- ---------------------- 3.7/8.2 MB 354.6 kB/s eta 0:00:13
   ----------------- ---------------------- 3.7/8.2 MB 354.6 kB/s eta 0:00:13
   ----------------- ---------------------- 3.7/8.2 MB 354.6 kB/s eta 0:00:13
   ------------------- -------------------- 3.9/8.2 MB 349.8 kB/s eta 0:00:13
   ------------------- -------------------- 3.9/8.2 MB 349.8 kB/s eta 0:00:13
   ------------------- -------------------- 3.9/8.2 MB 349.8 kB/s eta 0:00:13
   ------------------- -------------------- 3.9/8.2 MB 349.8 kB/s eta 0:00:13
   ------------------- -------------------- 3.9/8.2 MB 349.8 kB/s eta 0:00:13
   ------------------- -------------------- 3.9/8.2 MB 349.8 kB/s eta 0:00:13
   ------------------- -------------------- 3.9/8.2 MB 349.8 kB/s eta 0:00:13
   ------------------- -------------------- 3.9/8.2 MB 349.8 kB/s eta 0:00:13
   -------------------- ------------------- 4.2/8.2 MB 321.9 kB/s eta 0:00:13
   -------------------- ------------------- 4.2/8.2 MB 321.9 kB/s eta 0:00:13
   -------------------- ------------------- 4.2/8.2 MB 321.9 kB/s eta 0:00:13
   -------------------- ------------------- 4.2/8.2 MB 321.9 kB/s eta 0:00:13
   -------------------- ------------------- 4.2/8.2 MB 321.9 kB/s eta 0:00:13
   -------------------- ------------------- 4.2/8.2 MB 321.9 kB/s eta 0:00:13
   --------------------- ------------------ 4.5/8.2 MB 308.9 kB/s eta 0:00:13
   --------------------- ------------------ 4.5/8.2 MB 308.9 kB/s eta 0:00:13
   --------------------- ------------------ 4.5/8.2 MB 308.9 kB/s eta 0:00:13
   --------------------- ------------------ 4.5/8.2 MB 308.9 kB/s eta 0:00:13
   ---------------------- ----------------- 4.7/8.2 MB 309.5 kB/s eta 0:00:12
   ---------------------- ----------------- 4.7/8.2 MB 309.5 kB/s eta 0:00:12
   ---------------------- ----------------- 4.7/8.2 MB 309.5 kB/s eta 0:00:12
   ---------------------- ----------------- 4.7/8.2 MB 309.5 kB/s eta 0:00:12
   ---------------------- ----------------- 4.7/8.2 MB 309.5 kB/s eta 0:00:12
   ------------------------ --------------- 5.0/8.2 MB 308.2 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.2 MB 308.2 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.2 MB 308.2 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.2 MB 308.2 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.2 MB 308.2 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.2 MB 308.2 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.2 MB 308.2 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.2 MB 308.2 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.2 MB 308.2 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.2 MB 308.2 kB/s eta 0:00:11
   ------------------------- -------------- 5.2/8.2 MB 283.1 kB/s eta 0:00:11
   ------------------------- -------------- 5.2/8.2 MB 283.1 kB/s eta 0:00:11
   ------------------------- -------------- 5.2/8.2 MB 283.1 kB/s eta 0:00:11
   ------------------------- -------------- 5.2/8.2 MB 283.1 kB/s eta 0:00:11
   ------------------------- -------------- 5.2/8.2 MB 283.1 kB/s eta 0:00:11
   ------------------------- -------------- 5.2/8.2 MB 283.1 kB/s eta 0:00:11
   ------------------------- -------------- 5.2/8.2 MB 283.1 kB/s eta 0:00:11
   ------------------------- -------------- 5.2/8.2 MB 283.1 kB/s eta 0:00:11
   -------------------------- ------------- 5.5/8.2 MB 274.2 kB/s eta 0:00:10
   -------------------------- ------------- 5.5/8.2 MB 274.2 kB/s eta 0:00:10
   -------------------------- ------------- 5.5/8.2 MB 274.2 kB/s eta 0:00:10
   -------------------------- ------------- 5.5/8.2 MB 274.2 kB/s eta 0:00:10
   -------------------------- ------------- 5.5/8.2 MB 274.2 kB/s eta 0:00:10
   ---------------------------- ----------- 5.8/8.2 MB 272.3 kB/s eta 0:00:09
   ---------------------------- ----------- 5.8/8.2 MB 272.3 kB/s eta 0:00:09
   ---------------------------- ----------- 5.8/8.2 MB 272.3 kB/s eta 0:00:09
   ---------------------------- ----------- 5.8/8.2 MB 272.3 kB/s eta 0:00:09
   ---------------------------- ----------- 5.8/8.2 MB 272.3 kB/s eta 0:00:09
   ---------------------------- ----------- 5.8/8.2 MB 272.3 kB/s eta 0:00:09
   ----------------------------- ---------- 6.0/8.2 MB 268.1 kB/s eta 0:00:09
   ----------------------------- ---------- 6.0/8.2 MB 268.1 kB/s eta 0:00:09
   ----------------------------- ---------- 6.0/8.2 MB 268.1 kB/s eta 0:00:09
   ----------------------------- ---------- 6.0/8.2 MB 268.1 kB/s eta 0:00:09
   ----------------------------- ---------- 6.0/8.2 MB 268.1 kB/s eta 0:00:09
   ----------------------------- ---------- 6.0/8.2 MB 268.1 kB/s eta 0:00:09
   ----------------------------- ---------- 6.0/8.2 MB 268.1 kB/s eta 0:00:09
   ----------------------------- ---------- 6.0/8.2 MB 268.1 kB/s eta 0:00:09
   ----------------------------- ---------- 6.0/8.2 MB 268.1 kB/s eta 0:00:09
   ------------------------------ --------- 6.3/8.2 MB 258.5 kB/s eta 0:00:08
   ------------------------------ --------- 6.3/8.2 MB 258.5 kB/s eta 0:00:08
   ------------------------------ --------- 6.3/8.2 MB 258.5 kB/s eta 0:00:08
   ------------------------------ --------- 6.3/8.2 MB 258.5 kB/s eta 0:00:08
   ------------------------------ --------- 6.3/8.2 MB 258.5 kB/s eta 0:00:08
   ------------------------------ --------- 6.3/8.2 MB 258.5 kB/s eta 0:00:08
   ------------------------------- -------- 6.6/8.2 MB 255.8 kB/s eta 0:00:07
   ------------------------------- -------- 6.6/8.2 MB 255.8 kB/s eta 0:00:07
   ------------------------------- -------- 6.6/8.2 MB 255.8 kB/s eta 0:00:07
   ------------------------------- -------- 6.6/8.2 MB 255.8 kB/s eta 0:00:07
   ------------------------------- -------- 6.6/8.2 MB 255.8 kB/s eta 0:00:07
   --------------------------------- ------ 6.8/8.2 MB 255.3 kB/s eta 0:00:06
   --------------------------------- ------ 6.8/8.2 MB 255.3 kB/s eta 0:00:06
   --------------------------------- ------ 6.8/8.2 MB 255.3 kB/s eta 0:00:06
   --------------------------------- ------ 6.8/8.2 MB 255.3 kB/s eta 0:00:06
   --------------------------------- ------ 6.8/8.2 MB 255.3 kB/s eta 0:00:06
   ---------------------------------- ----- 7.1/8.2 MB 253.6 kB/s eta 0:00:05
   ---------------------------------- ----- 7.1/8.2 MB 253.6 kB/s eta 0:00:05
   ---------------------------------- ----- 7.1/8.2 MB 253.6 kB/s eta 0:00:05
   ---------------------------------- ----- 7.1/8.2 MB 253.6 kB/s eta 0:00:05
   ---------------------------------- ----- 7.1/8.2 MB 253.6 kB/s eta 0:00:05
   ---------------------------------- ----- 7.1/8.2 MB 253.6 kB/s eta 0:00:05
   ----------------------------------- ---- 7.3/8.2 MB 251.8 kB/s eta 0:00:04
   ----------------------------------- ---- 7.3/8.2 MB 251.8 kB/s eta 0:00:04
   ----------------------------------- ---- 7.3/8.2 MB 251.8 kB/s eta 0:00:04
   ----------------------------------- ---- 7.3/8.2 MB 251.8 kB/s eta 0:00:04
   ----------------------------------- ---- 7.3/8.2 MB 251.8 kB/s eta 0:00:04
   ----------------------------------- ---- 7.3/8.2 MB 251.8 kB/s eta 0:00:04
   ------------------------------------- -- 7.6/8.2 MB 250.9 kB/s eta 0:00:03
   ------------------------------------- -- 7.6/8.2 MB 250.9 kB/s eta 0:00:03
   ------------------------------------- -- 7.6/8.2 MB 250.9 kB/s eta 0:00:03
   ------------------------------------- -- 7.6/8.2 MB 250.9 kB/s eta 0:00:03
   ------------------------------------- -- 7.6/8.2 MB 250.9 kB/s eta 0:00:03
   ------------------------------------- -- 7.6/8.2 MB 250.9 kB/s eta 0:00:03
   ------------------------------------- -- 7.6/8.2 MB 250.9 kB/s eta 0:00:03
   ------------------------------------- -- 7.6/8.2 MB 250.9 kB/s eta 0:00:03
   ------------------------------------- -- 7.6/8.2 MB 250.9 kB/s eta 0:00:03
   ------------------------------------- -- 7.6/8.2 MB 250.9 kB/s eta 0:00:03
   ------------------------------------- -- 7.6/8.2 MB 250.9 kB/s eta 0:00:03
   -------------------------------------- - 7.9/8.2 MB 210.3 kB/s eta 0:00:02
   -------------------------------------- - 7.9/8.2 MB 210.3 kB/s eta 0:00:02
   -------------------------------------- - 7.9/8.2 MB 210.3 kB/s eta 0:00:02
   -------------------------------------- - 7.9/8.2 MB 210.3 kB/s eta 0:00:02
   -------------------------------------- - 7.9/8.2 MB 210.3 kB/s eta 0:00:02
   -------------------------------------- - 7.9/8.2 MB 210.3 kB/s eta 0:00:02
   -------------------------------------- - 7.9/8.2 MB 210.3 kB/s eta 0:00:02
   -------------------------------------- - 7.9/8.2 MB 210.3 kB/s eta 0:00:02
   -------------------------------------- - 7.9/8.2 MB 210.3 kB/s eta 0:00:02
   -------------------------------------- - 7.9/8.2 MB 210.3 kB/s eta 0:00:02
   ---------------------------------------  8.1/8.2 MB 197.6 kB/s eta 0:00:01
   ---------------------------------------  8.1/8.2 MB 197.6 kB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 197.7 kB/s eta 0:00:00
Using cached numpy-2.4.5-cp313-cp313-win_amd64.whl (12.3 MB)
Downloading pandas-3.0.3-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 243.6 kB/s eta 0:00:38
   -- ------------------------------------- 0.5/9.8 MB 243.6 kB/s eta 0:00:38
   -- ------------------------------------- 0.5/9.8 MB 243.6 kB/s eta 0:00:38
   -- ------------------------------------- 0.5/9.8 MB 243.6 kB/s eta 0:00:38
   -- ------------------------------------- 0.5/9.8 MB 243.6 kB/s eta 0:00:38
   -- ------------------------------------- 0.5/9.8 MB 243.6 kB/s eta 0:00:38
   -- ------------------------------------- 0.5/9.8 MB 243.6 kB/s eta 0:00:38
   --- ------------------------------------ 0.8/9.8 MB 196.6 kB/s eta 0:00:46
   --- ------------------------------------ 0.8/9.8 MB 196.6 kB/s eta 0:00:46
   --- ------------------------------------ 0.8/9.8 MB 196.6 kB/s eta 0:00:46
   --- ------------------------------------ 0.8/9.8 MB 196.6 kB/s eta 0:00:46
   --- ------------------------------------ 0.8/9.8 MB 196.6 kB/s eta 0:00:46
   --- ------------------------------------ 0.8/9.8 MB 196.6 kB/s eta 0:00:46
   ---- ----------------------------------- 1.0/9.8 MB 206.2 kB/s eta 0:00:43
   ---- ----------------------------------- 1.0/9.8 MB 206.2 kB/s eta 0:00:43
   ----- ---------------------------------- 1.3/9.8 MB 237.8 kB/s eta 0:00:36
   ----- ---------------------------------- 1.3/9.8 MB 237.8 kB/s eta 0:00:36
   ----- ---------------------------------- 1.3/9.8 MB 237.8 kB/s eta 0:00:36
   ----- ---------------------------------- 1.3/9.8 MB 237.8 kB/s eta 0:00:36
   ----- ---------------------------------- 1.3/9.8 MB 237.8 kB/s eta 0:00:36
   ------ --------------------------------- 1.6/9.8 MB 243.7 kB/s eta 0:00:34
   ------ --------------------------------- 1.6/9.8 MB 243.7 kB/s eta 0:00:34
   ------ --------------------------------- 1.6/9.8 MB 243.7 kB/s eta 0:00:34
   ------ --------------------------------- 1.6/9.8 MB 243.7 kB/s eta 0:00:34
   ------ --------------------------------- 1.6/9.8 MB 243.7 kB/s eta 0:00:34
   ------ --------------------------------- 1.6/9.8 MB 243.7 kB/s eta 0:00:34
   ------- -------------------------------- 1.8/9.8 MB 235.1 kB/s eta 0:00:34
   ------- -------------------------------- 1.8/9.8 MB 235.1 kB/s eta 0:00:34
   ------- -------------------------------- 1.8/9.8 MB 235.1 kB/s eta 0:00:34
   ------- -------------------------------- 1.8/9.8 MB 235.1 kB/s eta 0:00:34
   ------- -------------------------------- 1.8/9.8 MB 235.1 kB/s eta 0:00:34
   ------- -------------------------------- 1.8/9.8 MB 235.1 kB/s eta 0:00:34
   ------- -------------------------------- 1.8/9.8 MB 235.1 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 226.8 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 226.8 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 226.8 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 226.8 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 226.8 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 226.8 kB/s eta 0:00:34
   --------- ------------------------------ 2.4/9.8 MB 222.7 kB/s eta 0:00:34
   --------- ------------------------------ 2.4/9.8 MB 222.7 kB/s eta 0:00:34
   --------- ------------------------------ 2.4/9.8 MB 222.7 kB/s eta 0:00:34
   --------- ------------------------------ 2.4/9.8 MB 222.7 kB/s eta 0:00:34
   --------- ------------------------------ 2.4/9.8 MB 222.7 kB/s eta 0:00:34
   ---------- ----------------------------- 2.6/9.8 MB 224.6 kB/s eta 0:00:32
   ---------- ----------------------------- 2.6/9.8 MB 224.6 kB/s eta 0:00:32
   ---------- ----------------------------- 2.6/9.8 MB 224.6 kB/s eta 0:00:32
   ---------- ----------------------------- 2.6/9.8 MB 224.6 kB/s eta 0:00:32

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Ziad\anaconda3\Lib\site-packages\~umpy'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Ziad\anaconda3\Lib\site-packages\~andas'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.61.0 requires numpy<2.2,>=1.24, but you have numpy 2.4.5 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.4.5 which is incompatible.
sklearn-compat 0.1.3 requires scikit-learn<1.7,>=1.2, but you have scikit-learn 1.8.0 which is incompatible.
streamlit 1.45.1 requires pandas<3,>=1.4.0, but you have pandas 3.0.3 which is incompatible.

In [8]:
from mlxtend.frequent_patterns import apriori, association_rules

In [9]:
frequent_items = apriori(
    basket,
    min_support=0.02,
    use_colnames=True
)

frequent_items.head()

c:\Users\Ziad\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:175: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

    support                           itemsets
0  0.021692         (3 STRIPEY MICE FELTCRAFT)
1  0.039175           (6 RIBBONS RUSTIC CHARM)
2  0.025146  (60 CAKE CASES VINTAGE CHRISTMAS)
3  0.035452      (60 TEATIME FAIRY CAKE CASES)
4  0.027034   (72 SWEETHEART FAIRY CAKE CASES)

In [10]:
rules = association_rules(
    frequent_items,
    metric="confidence",
    min_threshold=0.3
)

rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].head()

,antecedents,consequents,support,confidence,lift
0,(ALARM CLOCK BAKELIKE RED ),(ALARM CLOCK BAKELIKE GREEN),0.028599,0.604333,14.194548
1,(ALARM CLOCK BAKELIKE GREEN),(ALARM CLOCK BAKELIKE RED ),0.028599,0.671736,14.194548
2,(ALARM CLOCK BAKELIKE RED ),(ALARM CLOCK BAKELIKE PINK),0.021368,0.451539,13.650778
3,(ALARM CLOCK BAKELIKE PINK),(ALARM CLOCK BAKELIKE RED ),0.021368,0.646003,13.650778
4,(SPACEBOY LUNCH BOX ),(DOLLY GIRL LUNCH BOX),0.022879,0.602273,18.119023

In [11]:
top_rules = rules.sort_values(by='lift', ascending=False)

top_rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].head(10)

,antecedents,consequents,support,confidence,lift
65,(PINK REGENCY TEACUP AND SAUCER),"(GREEN REGENCY TEACUP AND SAUCER, ROSES REGENC...",0.021045,0.701439,24.027846
64,"(GREEN REGENCY TEACUP AND SAUCER, ROSES REGENC...",(PINK REGENCY TEACUP AND SAUCER),0.021045,0.720887,24.027846
63,"(ROSES REGENCY TEACUP AND SAUCER , PINK REGENC...",(GREEN REGENCY TEACUP AND SAUCER),0.021045,0.894495,23.989564
66,(GREEN REGENCY TEACUP AND SAUCER),"(ROSES REGENCY TEACUP AND SAUCER , PINK REGENC...",0.021045,0.564399,23.989564
9,(PINK REGENCY TEACUP AND SAUCER),(GREEN REGENCY TEACUP AND SAUCER),0.024822,0.827338,22.188466
8,(GREEN REGENCY TEACUP AND SAUCER),(PINK REGENCY TEACUP AND SAUCER),0.024822,0.665702,22.188466
67,(ROSES REGENCY TEACUP AND SAUCER ),"(GREEN REGENCY TEACUP AND SAUCER, PINK REGENCY...",0.021045,0.498084,20.066300
62,"(GREEN REGENCY TEACUP AND SAUCER, PINK REGENCY...",(ROSES REGENCY TEACUP AND SAUCER ),0.021045,0.847826,20.066300
57,(PINK REGENCY TEACUP AND SAUCER),(ROSES REGENCY TEACUP AND SAUCER ),0.023527,0.784173,18.559754
56,(ROSES REGENCY TEACUP AND SAUCER ),(PINK REGENCY TEACUP AND SAUCER),0.023527,0.556833,18.559754

In [12]:
print("Number of generated rules:", len(rules))

Number of generated rules: 68

In [13]:
rules[['support', 'confidence', 'lift']].describe()

         support  confidence       lift
count  68.000000   68.000000  68.000000
mean    0.023624    0.521999  11.172875
std     0.002576    0.138801   5.683091
min     0.020181    0.302019   3.821865
25%     0.021368    0.408953   7.246029
50%     0.022987    0.495993   8.202583
75%     0.024984    0.616042  14.194548
max     0.029463    0.894495  24.027846

In [14]:
from mlxtend.frequent_patterns import fpgrowth

fp_items = fpgrowth(
    basket,
    min_support=0.02,
    use_colnames=True
)

fp_rules = association_rules(
    fp_items,
    metric="confidence",
    min_threshold=0.3
)

print("FP-Growth itemsets:", len(fp_items))
print("FP-Growth rules:", len(fp_rules))

fp_rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].sort_values(
    by="lift", ascending=False
).head(10)

c:\Users\Ziad\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:175: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

FP-Growth itemsets: 243
FP-Growth rules: 68

,antecedents,consequents,support,confidence,lift
52,(PINK REGENCY TEACUP AND SAUCER),"(GREEN REGENCY TEACUP AND SAUCER, ROSES REGENC...",0.021045,0.701439,24.027846
51,"(GREEN REGENCY TEACUP AND SAUCER, ROSES REGENC...",(PINK REGENCY TEACUP AND SAUCER),0.021045,0.720887,24.027846
53,(GREEN REGENCY TEACUP AND SAUCER),"(ROSES REGENCY TEACUP AND SAUCER , PINK REGENC...",0.021045,0.564399,23.989564
50,"(ROSES REGENCY TEACUP AND SAUCER , PINK REGENC...",(GREEN REGENCY TEACUP AND SAUCER),0.021045,0.894495,23.989564
46,(PINK REGENCY TEACUP AND SAUCER),(GREEN REGENCY TEACUP AND SAUCER),0.024822,0.827338,22.188466
45,(GREEN REGENCY TEACUP AND SAUCER),(PINK REGENCY TEACUP AND SAUCER),0.024822,0.665702,22.188466
54,(ROSES REGENCY TEACUP AND SAUCER ),"(GREEN REGENCY TEACUP AND SAUCER, PINK REGENCY...",0.021045,0.498084,20.066300
49,"(GREEN REGENCY TEACUP AND SAUCER, PINK REGENCY...",(ROSES REGENCY TEACUP AND SAUCER ),0.021045,0.847826,20.066300
47,(ROSES REGENCY TEACUP AND SAUCER ),(PINK REGENCY TEACUP AND SAUCER),0.023527,0.556833,18.559754
48,(PINK REGENCY TEACUP AND SAUCER),(ROSES REGENCY TEACUP AND SAUCER ),0.023527,0.784173,18.559754

In [15]:
print("FP-Growth itemsets:", len(fp_items))
print("FP-Growth rules:", len(fp_rules))

FP-Growth itemsets: 243
FP-Growth rules: 68

In [16]:
from itertools import combinations

vertical_data = {}

for product in basket.columns:
    vertical_data[product] = set(basket.index[basket[product] == 1])

num_transactions = len(basket)

min_support = 0.02
min_count = int(min_support * num_transactions)

frequent_1 = {
    frozenset([product]): tids
    for product, tids in vertical_data.items()
    if len(tids) >= min_count
}

print("Frequent 1-itemsets:", len(frequent_1))

Frequent 1-itemsets: 207

In [17]:
eclat_itemsets = []

items = list(frequent_1.items())

for i in range(len(items)):
    itemset1, tids1 = items[i]

    for j in range(i + 1, len(items)):
        itemset2, tids2 = items[j]

        combined_itemset = itemset1 | itemset2
        combined_tids = tids1 & tids2

        support = len(combined_tids) / num_transactions

        if support >= min_support:
            eclat_itemsets.append({
                "support": support,
                "itemsets": combined_itemset
            })

eclat_df = pd.DataFrame(eclat_itemsets)

print("ECLAT itemsets:", len(eclat_df))

eclat_df.sort_values(by='support', ascending=False).head(10)

ECLAT itemsets: 35

     support                                           itemsets
8   0.029463  (JUMBO BAG PINK POLKADOT, JUMBO BAG RED RETROS...
6   0.029193  (GREEN REGENCY TEACUP AND SAUCER, ROSES REGENC...
0   0.028599  (ALARM CLOCK BAKELIKE RED , ALARM CLOCK BAKELI...
23  0.028221  (LUNCH BAG RED RETROSPOT, LUNCH BAG PINK POLKA...
15  0.027898  (LUNCH BAG RED RETROSPOT, LUNCH BAG  BLACK SKU...
34  0.025254  (WOODEN FRAME ANTIQUE WHITE , WOODEN PICTURE F...
24  0.025200  (LUNCH BAG SPACEBOY DESIGN , LUNCH BAG RED RET...
14  0.025038  (LUNCH BAG PINK POLKADOT, LUNCH BAG  BLACK SKU...
3   0.024984  (GARDENERS KNEELING PAD KEEP CALM , GARDENERS ...
4   0.024822  (GREEN REGENCY TEACUP AND SAUCER, PINK REGENCY...

In [18]:
eclat_rules = []

support_dict = {}

for itemset, tids in frequent_1.items():
    support_dict[itemset] = len(tids) / num_transactions

for _, row in eclat_df.iterrows():
    support_dict[row["itemsets"]] = row["support"]

for _, row in eclat_df.iterrows():
    itemset = row["itemsets"]
    itemset_support = row["support"]

    for item in itemset:
        antecedent = frozenset([item])
        consequent = itemset - antecedent

        antecedent_support = support_dict.get(antecedent, 0)
        consequent_support = support_dict.get(consequent, 0)

        if antecedent_support > 0 and consequent_support > 0:
            confidence = itemset_support / antecedent_support
            lift = confidence / consequent_support

            if confidence >= 0.3:
                eclat_rules.append({
                    "antecedents": antecedent,
                    "consequents": consequent,
                    "support": itemset_support,
                    "confidence": confidence,
                    "lift": lift
                })

eclat_rules_df = pd.DataFrame(eclat_rules)

print("ECLAT rules:", len(eclat_rules_df))

eclat_rules_df.sort_values(by="lift", ascending=False).head(10)

ECLAT rules: 62

,antecedents,consequents,support,confidence,lift
9,(PINK REGENCY TEACUP AND SAUCER),(GREEN REGENCY TEACUP AND SAUCER),0.024822,0.827338,22.188466
8,(GREEN REGENCY TEACUP AND SAUCER),(PINK REGENCY TEACUP AND SAUCER),0.024822,0.665702,22.188466
56,(ROSES REGENCY TEACUP AND SAUCER ),(PINK REGENCY TEACUP AND SAUCER),0.023527,0.556833,18.559754
57,(PINK REGENCY TEACUP AND SAUCER),(ROSES REGENCY TEACUP AND SAUCER ),0.023527,0.784173,18.559754
11,(GREEN REGENCY TEACUP AND SAUCER),(ROSES REGENCY TEACUP AND SAUCER ),0.029193,0.782923,18.530185
12,(ROSES REGENCY TEACUP AND SAUCER ),(GREEN REGENCY TEACUP AND SAUCER),0.029193,0.690932,18.530185
5,(DOLLY GIRL LUNCH BOX),(SPACEBOY LUNCH BOX ),0.022879,0.688312,18.119023
4,(SPACEBOY LUNCH BOX ),(DOLLY GIRL LUNCH BOX),0.022879,0.602273,18.119023
6,(GARDENERS KNEELING PAD KEEP CALM ),(GARDENERS KNEELING PAD CUP OF TEA ),0.024984,0.612434,17.873424
7,(GARDENERS KNEELING PAD CUP OF TEA ),(GARDENERS KNEELING PAD KEEP CALM ),0.024984,0.729134,17.873424

In [19]:
comparison = pd.DataFrame({
    "Algorithm": ["Apriori", "FP-Growth", "ECLAT"],

    "Frequent Itemsets": [
        len(frequent_items),
        len(fp_items),
        len(eclat_df)
    ],

    "Generated Rules": [
        len(rules),
        len(fp_rules),
        len(eclat_rules_df)
    ],

    "Max Confidence": [
        rules["confidence"].max(),
        fp_rules["confidence"].max(),
        eclat_rules_df["confidence"].max()
    ],

    "Max Lift": [
        rules["lift"].max(),
        fp_rules["lift"].max(),
        eclat_rules_df["lift"].max()
    ]
})

comparison

   Algorithm  Frequent Itemsets  Generated Rules  Max Confidence   Max Lift
0    Apriori                243               68        0.894495  24.027846
1  FP-Growth                243               68        0.894495  24.027846
2      ECLAT                 35               62        0.827338  22.188466

In [21]:
import time

start = time.time()

apriori(
    basket,
    min_support=0.02,
    use_colnames=True
)

end = time.time()

print("Apriori Time:", end - start)

c:\Users\Ziad\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:175: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

Apriori Time: 7.49666166305542

In [22]:
start = time.time()

fpgrowth(
    basket,
    min_support=0.02,
    use_colnames=True
)

end = time.time()

print("FP-Growth Time:", end - start)

c:\Users\Ziad\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:175: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

FP-Growth Time: 5.274147272109985

In [23]:
start = time.time()

eclat_itemsets = []

items = list(frequent_1.items())

for i in range(len(items)):
    itemset1, tids1 = items[i]

    for j in range(i + 1, len(items)):
        itemset2, tids2 = items[j]

        combined_itemset = itemset1 | itemset2
        combined_tids = tids1 & tids2

        support = len(combined_tids) / num_transactions

        if support >= min_support:
            eclat_itemsets.append({
                "support": support,
                "itemsets": combined_itemset
            })

end = time.time()

print("ECLAT Time:", end - start)

ECLAT Time: 0.6723427772521973

In [24]:
runtime_comparison = pd.DataFrame({
    "Algorithm": ["Apriori", "FP-Growth", "ECLAT"],

    "Execution Time (sec)": [
        7.49,
        5.27,
        0.67
    ]
})

runtime_comparison

   Algorithm  Execution Time (sec)
0    Apriori                  7.49
1  FP-Growth                  5.27
2      ECLAT                  0.67

In [25]:
rules[['antecedents',
       'consequents',
       'support',
       'confidence',
       'lift']].head(10)

,antecedents,consequents,support,confidence,lift
0,(ALARM CLOCK BAKELIKE RED ),(ALARM CLOCK BAKELIKE GREEN),0.028599,0.604333,14.194548
1,(ALARM CLOCK BAKELIKE GREEN),(ALARM CLOCK BAKELIKE RED ),0.028599,0.671736,14.194548
2,(ALARM CLOCK BAKELIKE RED ),(ALARM CLOCK BAKELIKE PINK),0.021368,0.451539,13.650778
3,(ALARM CLOCK BAKELIKE PINK),(ALARM CLOCK BAKELIKE RED ),0.021368,0.646003,13.650778
4,(SPACEBOY LUNCH BOX ),(DOLLY GIRL LUNCH BOX),0.022879,0.602273,18.119023
5,(DOLLY GIRL LUNCH BOX),(SPACEBOY LUNCH BOX ),0.022879,0.688312,18.119023
6,(GARDENERS KNEELING PAD KEEP CALM ),(GARDENERS KNEELING PAD CUP OF TEA ),0.024984,0.612434,17.873424
7,(GARDENERS KNEELING PAD CUP OF TEA ),(GARDENERS KNEELING PAD KEEP CALM ),0.024984,0.729134,17.873424
8,(GREEN REGENCY TEACUP AND SAUCER),(PINK REGENCY TEACUP AND SAUCER),0.024822,0.665702,22.188466
9,(PINK REGENCY TEACUP AND SAUCER),(GREEN REGENCY TEACUP AND SAUCER),0.024822,0.827338,22.188466

In [26]:
fp_rules[['antecedents',
          'consequents',
          'support',
          'confidence',
          'lift']].head(10)

,antecedents,consequents,support,confidence,lift
0,(ALARM CLOCK BAKELIKE RED ),(ALARM CLOCK BAKELIKE GREEN),0.028599,0.604333,14.194548
1,(ALARM CLOCK BAKELIKE GREEN),(ALARM CLOCK BAKELIKE RED ),0.028599,0.671736,14.194548
2,(ALARM CLOCK BAKELIKE RED ),(ALARM CLOCK BAKELIKE PINK),0.021368,0.451539,13.650778
3,(ALARM CLOCK BAKELIKE PINK),(ALARM CLOCK BAKELIKE RED ),0.021368,0.646003,13.650778
4,(WOODEN FRAME ANTIQUE WHITE ),(WOODEN PICTURE FRAME WHITE FINISH),0.025254,0.577065,12.207962
5,(WOODEN PICTURE FRAME WHITE FINISH),(WOODEN FRAME ANTIQUE WHITE ),0.025254,0.534247,12.207962
6,(RED HANGING HEART T-LIGHT HOLDER),(WHITE HANGING HEART T-LIGHT HOLDER),0.024552,0.670103,6.300533
7,(LUNCH BAG RED RETROSPOT),(JUMBO BAG RED RETROSPOT),0.022933,0.329969,3.821865
8,(JUMBO BAG PINK POLKADOT),(JUMBO BAG RED RETROSPOT),0.029463,0.626866,7.260672
9,(JUMBO BAG RED RETROSPOT),(JUMBO BAG PINK POLKADOT),0.029463,0.341250,7.260672

In [27]:
eclat_rules_df.sort_values(
    by="lift",
    ascending=False
).head(10)

,antecedents,consequents,support,confidence,lift
9,(PINK REGENCY TEACUP AND SAUCER),(GREEN REGENCY TEACUP AND SAUCER),0.024822,0.827338,22.188466
8,(GREEN REGENCY TEACUP AND SAUCER),(PINK REGENCY TEACUP AND SAUCER),0.024822,0.665702,22.188466
56,(ROSES REGENCY TEACUP AND SAUCER ),(PINK REGENCY TEACUP AND SAUCER),0.023527,0.556833,18.559754
57,(PINK REGENCY TEACUP AND SAUCER),(ROSES REGENCY TEACUP AND SAUCER ),0.023527,0.784173,18.559754
11,(GREEN REGENCY TEACUP AND SAUCER),(ROSES REGENCY TEACUP AND SAUCER ),0.029193,0.782923,18.530185
12,(ROSES REGENCY TEACUP AND SAUCER ),(GREEN REGENCY TEACUP AND SAUCER),0.029193,0.690932,18.530185
5,(DOLLY GIRL LUNCH BOX),(SPACEBOY LUNCH BOX ),0.022879,0.688312,18.119023
4,(SPACEBOY LUNCH BOX ),(DOLLY GIRL LUNCH BOX),0.022879,0.602273,18.119023
6,(GARDENERS KNEELING PAD KEEP CALM ),(GARDENERS KNEELING PAD CUP OF TEA ),0.024984,0.612434,17.873424
7,(GARDENERS KNEELING PAD CUP OF TEA ),(GARDENERS KNEELING PAD KEEP CALM ),0.024984,0.729134,17.873424

In [28]:
comparison

   Algorithm  Frequent Itemsets  Generated Rules  Max Confidence   Max Lift
0    Apriori                243               68        0.894495  24.027846
1  FP-Growth                243               68        0.894495  24.027846
2      ECLAT                 35               62        0.827338  22.188466

In [29]:
runtime_comparison

   Algorithm  Execution Time (sec)
0    Apriori                  7.49
1  FP-Growth                  5.27
2      ECLAT                  0.67

In [30]:
rules[['support',
       'confidence',
       'lift']].describe()

         support  confidence       lift
count  68.000000   68.000000  68.000000
mean    0.023624    0.521999  11.172875
std     0.002576    0.138801   5.683091
min     0.020181    0.302019   3.821865
25%     0.021368    0.408953   7.246029
50%     0.022987    0.495993   8.202583
75%     0.024984    0.616042  14.194548
max     0.029463    0.894495  24.027846

In [31]:
product = "PINK REGENCY TEACUP AND SAUCER"

recommendations = rules[
    rules['antecedents'].apply(
        lambda x: product in list(x)
    )
]

recommendations[
    ['antecedents', 'consequents', 'confidence', 'lift']
].sort_values(by='confidence', ascending=False)

,antecedents,consequents,confidence,lift
63,"(ROSES REGENCY TEACUP AND SAUCER , PINK REGENC...",(GREEN REGENCY TEACUP AND SAUCER),0.894495,23.989564
62,"(GREEN REGENCY TEACUP AND SAUCER, PINK REGENCY...",(ROSES REGENCY TEACUP AND SAUCER ),0.847826,20.066300
9,(PINK REGENCY TEACUP AND SAUCER),(GREEN REGENCY TEACUP AND SAUCER),0.827338,22.188466
57,(PINK REGENCY TEACUP AND SAUCER),(ROSES REGENCY TEACUP AND SAUCER ),0.784173,18.559754
65,(PINK REGENCY TEACUP AND SAUCER),"(GREEN REGENCY TEACUP AND SAUCER, ROSES REGENC...",0.701439,24.027846